### ISSUE TITLE
Zero volume showing

### ISSUE THREAD

**Issue by wjmelements** [Uniswap/uniswap-info#104]
<img width="710" alt="Screen Shot 2020-03-12 at 10 56 03 AM" src="https://user-images.githubusercontent.com/799573/76550921-1de61280-6450-11ea-9c58-261b6a928129.png">

**Comment by wjmelements** [comment]
<img width="962" alt="Screen Shot 2020-03-12 at 2 09 00 AM" src="https://user-images.githubusercontent.com/799573/76554072-71596000-6452-11ea-9643-e70c44c98373.png">

**Comment by callil** [comment]
Fixed
