### ISSUE TITLE
Add more stablecoins to Uniprice and show weighting on hover

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-info#157]

**Comment by ianlapham** [comment]
Hover with rates added in last update, 

What stablecoins should be added next?

**Comment by haydenadams** [comment]
Would be great to show the weights. Could look like:

45% ETH-DAI
45% ETH-USDC
  5% ETH-USDT 
  5% ETH-TUSD

Also prob could use some ux love @callil
