### ISSUE TITLE
decimals / sig figs improvements

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-info#160]
Came up with some improvements to how we do decimals.

1) Don't show decimals for USD values >= $1000

2) When showing decimals in dollar values <$1000 always show at least 2 digits. So if something is $10.70 don't show $10.7

3) Always show at least two sig figs for values <$1. $0.0023 is a lot better than $0.002

**Comment by ianlapham** [comment]
Fixed in current version
