### ISSUE TITLE
NaN error thrown for chart when 0 returned for all y-axis values

### ISSUE THREAD

**Issue by conlan** [Uniswap/uniswap-info#17]
I'm getting a series of these errors in the Chart component when the data has 0.00 for each of the yAxis values (ie exchange with 0 trade volume for each day):

```
react-dom.development.js:3134 Error: <rect> attribute height: Expected length, "NaN".
```

It only started occurring after the tooltip also started appearing so maybe it's related to that push?

**Comment by mirshko** [comment]
its due to the custom bar component not having any default height / width attrs. will set defaults on the props like that. 👍

**Comment by mirshko** [comment]
@conlan verify its fixed please?

**Comment by conlan** [comment]
verified!
