### ISSUE TITLE
Add Sitewide (protocol wide) Statistics

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-info#2]
Moved issue from: 

https://github.com/conlan/uniswap-info/issues/5

**Comment by mirshko** [comment]
@conlan what is this for? 

internal api perf dashboard?

**Comment by haydenadams** [comment]
@mirshko This is the sitewide statistics page

**Comment by mirshko** [comment]
like GA? or something similar?

**Comment by mirshko** [comment]
closed due to it being part of #21
