### ISSUE TITLE
Is there anyway I can download historical data for a given exchange?

### ISSUE THREAD

**Issue by d-ontmindme** [Uniswap/uniswap-info#29]
It would be nice to be able to download the data for a given exchange (liquidity pool size, exchange rate, etc.) as CSV or JSON. Is this easy to do?

**Comment by d-ontmindme** [comment]
Solved the issue. 

Using a locally-hosted uniswap.info and inserting the code:

return (
      <div>
      <ReactTable ref={(r)=>this.reactTable=r}
        className="TokenPoolHistory -striped"
        data={data}
        columns={columns}
        showPageSizeOptions={false}
        defaultPageSize={10}
        minRows={10}
        resizable={false}
      />

      <CSVLink data={data} targert="_blank">Click me to download csv file</CSVLink>
      

      </div>

In the appropriate place in the index.js file in TokenPoolHistory. Will submit pull request.

**Comment by veridelisi** [comment]
How could I see LP's injections/drains, trade(swap), marginal price and price datas for each pool? Historical datas?

Dr.Engin YILMAZ
