### ISSUE TITLE
Add search bar in token list 

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-info#3]
Moved: https://github.com/conlan/uniswap-info/issues/9

Potentially can reuse the token dropdown from Uniswap.exchange

**Comment by mirshko** [comment]
@haydenadams will look into using dropdown from .exchange in the future, for now used `react-select`

this can be closed in #6

**Comment by mirshko** [comment]
<img width="466" alt="screenshot 2018-12-23 16 45 31" src="https://user-images.githubusercontent.com/8116716/50385217-2e3a9200-06d2-11e9-9395-b0c33cc640fe.png">
