### ISSUE TITLE
Value of share of liquidity

### ISSUE THREAD

**Issue by ThomasdenH** [Uniswap/uniswap-info#30]
It would be nice to see the value of the personal share of the liquidity converted to either of the tokens. It would be for each point in time:

- `personal share` * (`total Token liquidity` * `token price` + `total Eth liquidity`)
- `personal share` * (`total Token liquidity` + `total Eth liquidity` / `token price`)

This would allow for easy tracking of the value of the pooled resources.

**Comment by haydenadams** [comment]
Closing in favor of https://github.com/Uniswap/uniswap-info/issues/56
