### ISSUE TITLE
Old token appears in the search bar on uniswap.info

### ISSUE THREAD

**Issue by vi-dangvu** [Uniswap/uniswap-info#314]
As discussed @ianlapham ,

When i do research 'NRG' on the search bar from uniswap.info, NRGT appears under token. Can we update that as well?

![image](https://user-images.githubusercontent.com/73355789/98739538-7126b100-23a1-11eb-8261-2c221e64304a.png)

Thanks,
Vi

**Comment by zalam003** [comment]
Some more information.  In the subgraph, we are still seeing NRGT as the symbol:
https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2
```
{
  tokens(where: 
    {id: "0x1416946162b1c2c871a73b07e932d2fb6c932069"}) 
  {
    symbol
    name
    decimals
  }
}
```

Result:
```
{
  "data": {
    "tokens": [
      {
        "decimals": "18",
        "name": "Energi",
        "symbol": "NRGT"
      }
    ]
  }
}
```

We see the same ticker in: https://raw.githubusercontent.com/jab416171/uniswap-pairtokens/master/uniswap_pair_tokens.json

The symbol has been updated to NRGE in etherscan.  We would appreciate if you could update subgraph.

**Comment by ianlapham** [comment]
@zalam003 The subgraph cant be changed on the spot like that. This is not something we control but a database on the graph's end. I can fix the search on the site though.

**Comment by zalam003** [comment]
> The subgraph cant be changed on the spot like that. This is not something we control but a database on the graph's end.

@ianlapham We were not aware of that there is already an automated resync process.  We will wait until that occurs.

> I can fix the search on the site though.

That will help a lot.  We are trying to make sure users are not confused when they are on Uniswap and Etherscan.  We want them to see the same token.  Other than the logo on Etherscan, we are all set there.  Once the search is changed in Uniswap, we should be good to go.

**Comment by vi-dangvu** [comment]
@ianlapham Hi Ian, i can still reproduce the issue on my side, is it normal?

Thanks,
Vi

**Comment by zalam003** [comment]
The search is fixed
![image](https://user-images.githubusercontent.com/48445346/99116571-39e31a80-25c2-11eb-9949-d2aa8151f50f.png)

**Comment by ianlapham** [comment]
Yep should be all set now on the client. Will start a sync on the subgraph that will get the change in there too, annoyingly will take a few weeks to sync there.
