### ISSUE TITLE
Large markets stuck loading blocks

### ISSUE THREAD

**Issue by tobutridaz** [Uniswap/uniswap-info#32]
Large markets like DAI or MKR are stuck loading blocks at around block number 7027947. 

Noticed on reddit:
https://new.reddit.com/r/UniSwap/comments/beqemo/uniswapinfo_mkr_market_getting_stuck_loading/
or
https://new.reddit.com/r/UniSwap/comments/bds45u/uniswap_dashboard/el36klp

**Comment by PhABC** [comment]
Related error ; 

![image](https://user-images.githubusercontent.com/9306422/57083091-01bd0500-6cc6-11e9-8e8f-91629cb3e0ca.png)

**Comment by kveretennicov** [comment]
> RPC Error: query returned more than 1000 results

Workaround is to reduce the page size in https://github.com/Uniswap/uniswap-info/blob/master/src/App.js#L452

More robust solution would be to handle this error specifically and to dynamically halve and double the page size based on what values work.
