### ISSUE TITLE
Wrong color for "Symbol" label on iPhone

### ISSUE THREAD

**Issue by JustinDrake** [Uniswap/uniswap-info#344]
Notice that the "Symbol" text under "Top Tokens" is black on grey when it should be white on grey.

![image](https://user-images.githubusercontent.com/731743/106368248-2da86700-6340-11eb-90b2-81d3a3480ef2.png)

**Comment by callil** [comment]
fixed in: https://github.com/Uniswap/uniswap-info/commit/583479de859ecac1fcdc5d6b49df7d5f0fbb939c
