### ISSUE TITLE
HOT token points to Hydro Protocol rather than Holo

### ISSUE THREAD

**Issue by thedavidmeister** [Uniswap/uniswap-info#36]
current:
contract is https://etherscan.io/address/0x9af839687f6c94542ac5ece2e317daae355493a1

HOT used by uniswap is HoloToken:

exchange: https://etherscan.io/address/0xd4777e164c6c683e10593e08760b803d58529a8e
token: https://etherscan.io/token/0x6c6ee5e31d828de241282b9606c8e98ea48526e2

**Comment by yinzeus** [comment]
The address you point to does not have any liquidity:
contract HydroToken is StandardToken {
  string constant public name = "Hydro Protocol Token";
  string constant public symbol = "HOT";
  uint8 constant public decimals = 18;
  uint public totalSupply = 1560000000 * 10**18;

Token:
0x9af839687f6c94542ac5ece2e317daae355493a1
Exchange Address on mainnet: (zero ether!)
0xe123575bF28aB05A65DE145061ba747887DeeAE3

When I look at HoloToken they are actively funded.
contract HoloToken is Ownable {
  string public constant name = "HoloToken";
  string public constant symbol = "HOT";
  uint8 public constant decimals = 18;
  
Token:
0x6c6EE5e31d828De241282B9606C8e98Ea48526E2

Exchange Address on mainnet: (61 ether)
0xd4777E164c6C683E10593E08760B803D58529a8E
