### ISSUE TITLE
Calculcation on share is incorrect on MOD, a 0 decimal Token

### ISSUE THREAD

**Issue by martinkrung** [Uniswap/uniswap-info#37]
MOD Token on unsiwap:
https://etherscan.io/token/0x957c30ab0426e0c93cd8241e2c60392d08c6ac8e

How it looks on unsiwap.info

![AwesomeScreenshot-Uniswap-Info-2019-07-02-10-07-79](https://user-images.githubusercontent.com/918180/60495514-3bec5800-9cb1-11e9-95f0-f6de7c618e51.png)

**Comment by Leibniz137** [comment]
I think this is actually a bug in the uniswap api `https://uniswap-api.loanscan.io/v1/user` url
