### ISSUE TITLE
Deeplinking like on uniswap.exchange

### ISSUE THREAD

**Issue by martinkrung** [Uniswap/uniswap-info#39]
Deeplinking would make it more easy to link from outside directly to a stat

This works uniswap.exchange:
https://uniswap.exchange/swap/0xc719d010B63E5bbF2C0551872CD5316ED26AcD83

This how it should work on uniswap.info:
https://uniswap.info/0xc719d010B63E5bbF2C0551872CD5316ED26AcD83

thanks..

**Comment by NoahZinsmeister** [comment]
this is live! e.g. https://uniswap.info/token/0x09cabec1ead1c0ba254b09efb3ee13841712be14
