### ISSUE TITLE
application keeps crashing in mozilla

### ISSUE THREAD

**Issue by BOR4** [Uniswap/uniswap-info#394]
https://user-images.githubusercontent.com/40821065/117417304-7e6cc480-af1a-11eb-9f75-a8ecee84bca1.mp4

![image](https://user-images.githubusercontent.com/40821065/117417397-980e0c00-af1a-11eb-9dd0-0ae01b9a3de7.png)
![image](https://user-images.githubusercontent.com/40821065/117417489-b542da80-af1a-11eb-8153-17945006628a.png)

This is only in mozzilla. I am able to open it without issues in Chrome. I use Linux ubuntu.
Had same issue yesterday but after several hard refreshes it worked.

**Comment by willhennessy** [comment]
seems to be working now
