### ISSUE TITLE
Cannot open uniswap account info in any browser

### ISSUE THREAD

**Issue by neonhummer** [Uniswap/uniswap-info#399]
https://info.uniswap.org/account/
after that goes account number with
https://info.uniswap.org/account/(wallet number)

**Comment by willhennessy** [comment]
Hi neonhummer, there is no 'account' info in the uniswap app. If you want to view trade history, please visit a tool like etherscan. If you want to view the current balance of an LP position, you can check https://app.uniswap.org/#/pool
