### ISSUE TITLE
Use Infura in fallback for when no web3 detected

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-info#4]
Moved: https://github.com/conlan/uniswap-info/issues/10

**Comment by mirshko** [comment]
@conlan is it possible to add https://noahzinsmeister.gitbook.io/web3-react/ the new version of web3-react with the nice walletconnect and infura hookups this looks like it handles alot of this for us! 

here is the live demo https://codesandbox.io/s/w68nr06x77

**Comment by conlan** [comment]
@mirshko sure thing, do we wanna do this on build-redesign branch or update it on a new branch? Also what version do you want to update it to, 2.0.5? https://www.npmjs.com/package/web3-react/v/2.0.5

**Comment by mirshko** [comment]
lets do it on redesign and use the latest version :)

**Comment by mirshko** [comment]
done in new version
