### ISSUE TITLE
Update DNS to point at uniswap.github

### ISSUE THREAD

**Issue by conlan** [Uniswap/uniswap-info#5]

**Comment by conlan** [comment]
Actually, gonna re-assign to @mirshko since he's spearheading with Netlify.

**Comment by haydenadams** [comment]
@conlan Was talking with @mirshko in DMs a few days ago and I think we decided to stay GH-pages for now.

**Comment by mirshko** [comment]
@haydenadams @conlan yeah for now since .exchange and the website is gh pages makes sense to keep them all the same. maybe move to zeit now team (because of the nice lambdas n such) / netlify teams

**Comment by conlan** [comment]
Okay sounds good then! In that case I can re-assign myself to point the DNS to this github project.

**Comment by haydenadams** [comment]
@conlan I think you also have to delete the CNAME from the old repo for it to work
