### ISSUE TITLE
Price mismatch between uniswap.exchange & uniswap.info, sometimes negative

### ISSUE THREAD

**Issue by brandoniles** [Uniswap/uniswap-info#74]
I noticed that uniswap.info consistently under-reports the price on the AMPL exchange for both USD and ETH. You can see this directly by loading:
1) 1 AMPL = 0.002467 ETH on [uniswap.exchange](https://uniswap.exchange/swap/0xd46ba6d942050d489dbd938a2c909a5d5039a161)
2) 1 AMPL = 0.0009 ETH on [uniswap.info](https://uniswap.info/token/0xd46ba6d942050d489dbd938a2c909a5d5039a161)

In this screencap the price actually goes negative:
<img width="835" alt="Screen Shot 2019-11-06 at 1 31 01 PM" src="https://user-images.githubusercontent.com/544485/68339589-bd0d8e80-0099-11ea-94d8-b2543abe6fb6.png">

**Comment by callil** [comment]
I believe this has been fixed as of V2
