### ISSUE TITLE
Loading indicator for slow populating fields

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-info#89]
Liquidity / volume / price change load way slower than the other fields. Might be useful to have some loading indicator for them

<img width="1485" alt="Screen Shot 2019-12-12 at 6 05 05 PM" src="https://user-images.githubusercontent.com/9343483/70756248-0b9df080-1d0a-11ea-9248-1af2babc3294.png">

**Comment by callil** [comment]
I think this one is solved by the running unicorn right now
